### ISSUE TITLE
Missing executable for Windows and Linux. Also no apk file for android

### ISSUE THREAD

**Issue by Apacelus** [Jazzeus/Calculator#1]
I have noticed your latest release does not have any executables. I thought you might've forgotten to add those. Also please consider making an Android app, because there are not enought calculators for android.

**Comment by Jazzeus** [comment]
> I have noticed your latest release does not have any executables. I thought you might've forgotten to add those. Also please consider making an Android app, because there are not enought calculators for android.

Probably when the calculator is finished. 
And an Android app isn't worth it because we both know there too many calculators out there.
